# Generated by Django 3.0.2 on 2020-01-07 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200107_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dewey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type_publication', models.CharField(max_length=30)),
                ('genre', models.CharField(blank=True, max_length=30, null=True)),
                ('reference', models.CharField(blank=True, max_length=30, null=True)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('nb_tracks_pages', models.IntegerField(blank=True, null=True)),
                ('label_editor', models.CharField(blank=True, max_length=30, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.Author')),
                ('dewey_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.Dewey')),
            ],
        ),
    ]
