# Generated by Django 3.0.2 on 2020-01-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200107_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dewey',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['reference']},
        ),
        migrations.AlterField(
            model_name='publication',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True),
        ),
    ]
