# Generated by Django 3.0.2 on 2020-01-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_publication_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dewey',
            name='bg_color',
            field=models.CharField(choices=[('000', '#000000'), ('111', '#8B4513'), ('222', '#FF0000'), ('333', '#FF4500'), ('444', '#FFFF00'), ('555', '#32CD32'), ('666', '#1E90FF'), ('777', '#8B008B'), ('888', '#A9A9A9'), ('999', '#FFFFFF')], default=999, max_length=7),
        ),
        migrations.AddField(
            model_name='dewey',
            name='text_color',
            field=models.CharField(choices=[('white', 'FFFFFF'), ('black', '000000')], default=0, max_length=7),
        ),
    ]
